# Generated by Django 4.0.4 on 2022-04-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
