# Generated by Django 4.0.4 on 2022-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funame',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User_Registration',
        ),
    ]
