# Generated by Django 4.0.4 on 2022-04-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0006_alter_member_email_alter_member_funame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='pass1',
            new_name='confirm_Password',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='pass2',
            new_name='password',
        ),
    ]
