# Generated by Django 4.0.4 on 2022-04-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0011_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
