# Generated by Django 4.0.4 on 2022-04-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0013_alter_profile_token_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
