# Generated by Django 4.0.4 on 2022-04-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='htmlcss.member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
