# Generated by Django 4.0.4 on 2022-04-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
