# Generated by Django 4.0.4 on 2022-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('fb', models.CharField(max_length=100)),
                ('userimg', models.ImageField(upload_to='UserPhoto')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
