# Generated by Django 4.0.4 on 2022-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfcard',
            old_name='email',
            new_name='email1',
        ),
    ]
